/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaCode;

import java.util.PriorityQueue;

public class App {

    public static void main(String[] args) {
        int[][]matrix = {{1,5,9},{10,11},{12,13,15}};
        int k = 6;
        kthSmallest(matrix,k);
    }
    static public void kthSmallest(int[][] matrix, int k) {
        PriorityQueue<Integer> nm=new PriorityQueue<>();
        for(int i=0;i<matrix.length;i++)
        {
            for(int j=0;j<matrix[i].length;j++)
            {
                nm.add(matrix[i][j]);
            }
        }
        System.out.println(nm);

        while(k-->1)
        {
            nm.poll();
        }
        System.out.println(nm.poll());
    }
}
